/**
 * QR Decomposition (Householder) — OpenMP parallel benchmark
 * Amdahl's Law analysis + automatic chart generation
 *
 * Build (Linux/macOS):
 *   g++ -O2 -fopenmp -o qr_benchmark qr_openmp.cpp
 *
 * Build (Windows, Visual Studio):
 *   Project Properties -> C/C++ -> Language -> OpenMP Support -> Yes
 *
 * Requirements for charts:
 *   pip install matplotlib pandas numpy
 *
 * Output files (same folder as .exe):
 *   benchmark_results.csv
 *   plot_results.py
 *   chart_amdahl.png
 *   chart_speedup.png
 *   chart_efficiency.png
 *   chart_time.png
 */

#include <iostream>
#include <vector>
#include <cmath>
#include <chrono>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>
#include <random>
#include <algorithm>
#include <omp.h>

#ifdef _WIN32
#include <windows.h>
#endif

using namespace std;
using Matrix = vector<vector<double>>;
using Clock = chrono::high_resolution_clock;

struct BenchResult {
    int    n;
    int    threads;
    double time_ms;
    double speedup;
    double efficiency;
    double amdahl_speedup;
};

// ── Random matrix ─────────────────────────────────────────────────────────────
Matrix make_random(int n, unsigned seed = 42) {
    mt19937_64 rng(seed);
    uniform_real_distribution<double> dist(-10.0, 10.0);
    Matrix A(n, vector<double>(n));
    for (int i = 0; i < n; i++)
        for (int j = 0; j < n; j++)
            A[i][j] = dist(rng);
    return A;
}

// ── Sequential QR (Householder) ───────────────────────────────────────────────
void qr_sequential(Matrix A, Matrix& Q, Matrix& R) {
    int n = (int)A.size();
    Q.assign(n, vector<double>(n, 0.0));
    for (int i = 0; i < n; i++) Q[i][i] = 1.0;
    R = A;
    for (int k = 0; k < n - 1; k++) {
        vector<double> v(n - k);
        double sigma = 0.0;
        for (int i = k; i < n; i++) { v[i - k] = R[i][k]; sigma += v[i - k] * v[i - k]; }
        double nrm = sqrt(sigma);
        v[0] += (v[0] >= 0.0 ? nrm : -nrm);
        double nv2 = 0.0;
        for (double vi : v) nv2 += vi * vi;
        if (nv2 < 1e-14) continue;
        double inv = 1.0 / nv2;
        for (int j = k; j < n; j++) {
            double d = 0.0;
            for (int i = k; i < n; i++) d += v[i - k] * R[i][j];
            d *= 2.0 * inv;
            for (int i = k; i < n; i++) R[i][j] -= d * v[i - k];
        }
        for (int i = 0; i < n; i++) {
            double d = 0.0;
            for (int j = k; j < n; j++) d += Q[i][j] * v[j - k];
            d *= 2.0 * inv;
            for (int j = k; j < n; j++) Q[i][j] -= d * v[j - k];
        }
    }
}

// ── Parallel QR (OpenMP) ──────────────────────────────────────────────────────
void qr_parallel(Matrix A, Matrix& Q, Matrix& R, int num_threads) {
    int n = (int)A.size();
    Q.assign(n, vector<double>(n, 0.0));
    for (int i = 0; i < n; i++) Q[i][i] = 1.0;
    R = A;
    omp_set_num_threads(num_threads);
    for (int k = 0; k < n - 1; k++) {
        vector<double> v(n - k);
        double sigma = 0.0;
        for (int i = k; i < n; i++) { v[i - k] = R[i][k]; sigma += v[i - k] * v[i - k]; }
        double nrm = sqrt(sigma);
        v[0] += (v[0] >= 0.0 ? nrm : -nrm);
        double nv2 = 0.0;
        for (double vi : v) nv2 += vi * vi;
        if (nv2 < 1e-14) continue;
        double inv = 1.0 / nv2;
#pragma omp parallel for schedule(static)
        for (int j = k; j < n; j++) {
            double d = 0.0;
            for (int i = k; i < n; i++) d += v[i - k] * R[i][j];
            d *= 2.0 * inv;
            for (int i = k; i < n; i++) R[i][j] -= d * v[i - k];
        }
#pragma omp parallel for schedule(static)
        for (int i = 0; i < n; i++) {
            double d = 0.0;
            for (int j = k; j < n; j++) d += Q[i][j] * v[j - k];
            d *= 2.0 * inv;
            for (int j = k; j < n; j++) Q[i][j] -= d * v[j - k];
        }
    }
}

double bench(int n, int t, int reps = 3) {
    auto A = make_random(n);
    double total = 0.0;
    Matrix Q, R;
    for (int r = 0; r < reps; r++) {
        auto t0 = Clock::now();
        if (t == 1) qr_sequential(A, Q, R);
        else        qr_parallel(A, Q, R, t);
        auto t1 = Clock::now();
        total += chrono::duration<double, milli>(t1 - t0).count();
    }
    return total / reps;
}

string speedup_bar(double s, double ideal) {
    int filled = max(0, min(20, (int)(s / ideal * 20)));
    return "[" + string(filled, '#') + string(20 - filled, '.') + "]";
}

// ── Write the Python plotting script ─────────────────────────────────────────
void write_plot_script(const string& csv_path, const string& script_path,
    const vector<int>& sizes, const vector<int>& threads,
    double p_parallel, int hw_threads) {
    ofstream f(script_path);
    f << R"(# -*- coding: utf-8 -*-
"""
Auto-generated by qr_openmp.cpp
Run:  python plot_results.py
Requires: pip install matplotlib pandas numpy
"""
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import sys, os

CSV  = os.path.join(os.path.dirname(__file__), 'benchmark_results.csv')
OUT  = os.path.dirname(__file__)
P    = )" << p_parallel << R"(
HW   = )" << hw_threads << R"(

df      = pd.read_csv(CSV)
sizes   = sorted(df['matrix_size'].unique())
threads = sorted(df['threads'].unique())
c5      = ['#1F3864','#2F5496','#4472C4','#70AD47','#ED7D31']
mk      = ['o','s','^','D','v']
plt.rcParams.update({'font.size': 11, 'axes.spines.top': False, 'axes.spines.right': False})

# ── 1. Amdahl's Law ────────────────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle("Amdahl's Law - Theoretical vs Real Speedup", fontsize=15, fontweight='bold')

p_vals  = [0.50, 0.70, P, 0.90, 0.95]
p_lbls  = ['p=0.50', 'p=0.70', f'p={P} (our QR)', 'p=0.90', 'p=0.95']
pal     = plt.cm.plasma(np.linspace(0.1, 0.9, len(p_vals)))
n_disc  = np.array([1,2,4,8,16,32,64,128])
n_cont  = np.linspace(1, 128, 600)

# Left — discrete, real data overlaid
for pv, col, lbl in zip(p_vals, pal, p_lbls):
    sp = 1/((1-pv) + pv/n_disc)
    lw = 3 if pv==P else 1.8
    ls = '-' if pv==P else '--'
    ax1.plot(n_disc, sp, ls, color=col, lw=lw, marker='o',
             ms=6 if pv==P else 4, zorder=5 if pv==P else 3, label=lbl)
ax1.plot(n_disc, n_disc, 'k:', lw=1.5, alpha=0.5, label='Ideal S=N')

# Overlay real data (largest two matrices)
real_cols = ['#C00000', '#FF6B35']
for ci, n in enumerate(sorted(sizes)[-2:]):
    sub = df[df['matrix_size']==n]
    sym = 'v' if ci==1 else '^'
    ax1.plot(sub['threads'], sub['speedup'], sym,
             color=real_cols[ci], ms=11, zorder=10,
             label=f'Real {n}x{n}',
             markeredgecolor='white', markeredgewidth=1.2)

smax = 1/(1-P)
ax1.axhline(y=smax, color='#C00000', ls=':', lw=2, alpha=0.6)
ax1.text(1.2, smax+0.25, f'S_max = {smax:.2f}x (p={P})',
         color='#C00000', fontsize=9, fontweight='bold')
ax1.set_xscale('log', base=2)
ax1.set_xticks([1,2,4,8,16,32,64,128])
ax1.set_xticklabels([1,2,4,8,16,32,64,128])
ax1.set_xlabel('Number of threads N', fontsize=12)
ax1.set_ylabel('Speedup S(N)', fontsize=12)
ax1.set_title('Amdahl curves + real benchmark data', fontsize=12, fontweight='bold')
ax1.legend(fontsize=8, loc='upper left', framealpha=0.9)
ax1.grid(True, alpha=0.3)

# Right — continuous curves with asymptote labels
for pv, col, lbl in zip(p_vals, pal, p_lbls):
    sp = 1/((1-pv) + pv/n_cont)
    lw = 3 if pv==P else 1.5
    ls = '-' if pv==P else '--'
    ax2.plot(n_cont, sp, ls, color=col, lw=lw, label=lbl)
    sm = round(1/(1-pv), 1)
    ax2.axhline(y=sm, color=col, ls=':', lw=0.9, alpha=0.5)
    ax2.text(131, sm+0.15, f'{sm}x', color=col, fontsize=8,
             va='bottom', fontweight='bold')
ax2.plot(n_cont, np.minimum(n_cont, 20), 'k:', lw=1.5, alpha=0.4, label='Ideal S=N')
ax2.set_xlim(0, 148); ax2.set_ylim(0, 22)
ax2.annotate(f'Our QR limit\nS_max = {smax:.2f}x',
             xy=(128, smax), xytext=(85, smax+3.5),
             arrowprops=dict(arrowstyle='->', color='#C00000', lw=1.5),
             fontsize=9, color='#C00000', fontweight='bold')
ax2.set_xlabel('Number of threads N', fontsize=12)
ax2.set_ylabel('Speedup S(N)', fontsize=12)
ax2.set_title('Continuous curves — S_max asymptotes', fontsize=12, fontweight='bold')
ax2.legend(fontsize=8, loc='upper left', framealpha=0.9)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
out = os.path.join(OUT, 'chart_amdahl.png')
plt.savefig(out, dpi=150, bbox_inches='tight')
plt.close()
print(f'  [OK] chart_amdahl.png')

# ── 2. Speedup real vs Amdahl per matrix size ──────────────────────────────
fig, axes = plt.subplots(1, len(sizes), figsize=(4*len(sizes), 4.5))
fig.suptitle('Real Speedup vs Amdahl Theory per Matrix Size',
             fontsize=13, fontweight='bold')
for idx, (ax, n) in enumerate(zip(axes, sizes)):
    sub = df[df['matrix_size']==n]
    ax.plot(sub['threads'], sub['speedup'],
            'o-', color='#C00000', lw=2.5, ms=8, label='Real S', zorder=5)
    ax.plot(sub['threads'], sub['amdahl_speedup'],
            's--', color='#4472C4', lw=2, ms=7, label='Amdahl S', zorder=4)
    ax.plot(sub['threads'], sub['threads'].astype(float),
            ':', color='#70AD47', lw=1.5, label='Ideal S=N')
    ax.fill_between(sub['threads'], sub['speedup'], sub['amdahl_speedup'],
                    alpha=0.12, color='orange', label='Overhead gap')
    ax.set_title(f'{n}x{n}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Threads', fontsize=9)
    if idx == 0: ax.set_ylabel('Speedup S', fontsize=10)
    ax.set_xticks(threads)
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)
plt.tight_layout()
out = os.path.join(OUT, 'chart_speedup.png')
plt.savefig(out, dpi=150, bbox_inches='tight')
plt.close()
print(f'  [OK] chart_speedup.png')

# ── 3. Efficiency heatmap ──────────────────────────────────────────────────
th4 = [t for t in threads if t > 1]
fig, ax = plt.subplots(figsize=(2.4*len(th4), 5))
mat = np.array([[df[(df['matrix_size']==n)&(df['threads']==t)]['efficiency_pct'].values[0]
                 for t in th4] for n in sizes])
im = ax.imshow(mat, cmap='RdYlGn', aspect='auto', vmin=0, vmax=110)
ax.set_xticks(range(len(th4)))
ax.set_xticklabels([f'T={t}' for t in th4], fontsize=12)
ax.set_yticks(range(len(sizes)))
ax.set_yticklabels([f'{n}x{n}' for n in sizes], fontsize=12)
ax.set_title('Parallel Efficiency E (%)\n>100% = superlinear speedup (cache effect)',
             fontsize=12, fontweight='bold')
for i in range(len(sizes)):
    for j in range(len(th4)):
        v = mat[i, j]
        ax.text(j, i, f'{v:.1f}%', ha='center', va='center',
                fontsize=11, fontweight='bold',
                color='black' if v > 45 else 'white')
plt.colorbar(im, label='Efficiency (%)')
plt.tight_layout()
out = os.path.join(OUT, 'chart_efficiency.png')
plt.savefig(out, dpi=150, bbox_inches='tight')
plt.close()
print(f'  [OK] chart_efficiency.png')

# ── 4. Execution time ──────────────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('QR Decomposition - Execution Time vs Thread Count',
             fontsize=13, fontweight='bold')
for i, n in enumerate(sizes):
    sub = df[df['matrix_size']==n]
    kw = dict(marker=mk[i%len(mk)], color=c5[i%len(c5)], lw=2, ms=7, label=f'{n}x{n}')
    ax1.plot(sub['threads'], sub['time_ms'], **kw)
    ax2.plot(sub['threads'], sub['time_ms'], **kw)
for ax, ttl, logy in [(ax1, 'Log scale', True), (ax2, 'Linear scale', False)]:
    ax.set_xlabel('OpenMP threads', fontsize=11)
    ax.set_ylabel('Time (ms)', fontsize=11)
    ax.set_title(ttl, fontsize=11)
    ax.set_xticks(threads)
    ax.legend(title='Matrix size', fontsize=9)
    ax.grid(True, alpha=0.4)
    if logy: ax.set_yscale('log')
plt.tight_layout()
out = os.path.join(OUT, 'chart_time.png')
plt.savefig(out, dpi=150, bbox_inches='tight')
plt.close()
print(f'  [OK] chart_time.png')

print('\nAll charts saved to:', OUT)
)";
    f.close();
}

// ── Try to run Python ─────────────────────────────────────────────────────────
bool run_python(const string& script) {
    vector<string> cmds = {
        "py",                      // Windows Python Launcher (most reliable on Windows)
        "python",
        "python3",
        "%LOCALAPPDATA%\\Programs\\Python\\Python312\\python",
        "%LOCALAPPDATA%\\Programs\\Python\\Python311\\python",
        "%LOCALAPPDATA%\\Programs\\Python\\Python310\\python",
    };
    for (auto& py : cmds) {
        string cmd = py + " \"" + script + "\" 2>nul";
#ifndef _WIN32
        cmd = py + " \"" + script + "\" 2>/dev/null";
#endif
        int ret = system(cmd.c_str());
        if (ret == 0) return true;
    }
    return false;
}

int main() {
#ifdef _WIN32
    SetConsoleOutputCP(CP_UTF8);
#endif

    const double p = 0.82;
    vector<int> sizes = { 64, 128, 256, 512, 1024 };
    vector<int> threads = { 1, 2, 4, 8, 16 };
    int hw_threads = omp_get_max_threads();

    cout << "\n";
    cout << "+==============================================================+\n";
    cout << "|   QR Decomposition (Householder) - OpenMP Benchmark          |\n";
    cout << "|   Amdahl Law: S(n) = 1 / ((1-p) + p/n),  p = 0.82          |\n";
    cout << "+==============================================================+\n";
    cout << "  Hardware threads: " << hw_threads << "\n";
    cout << "  Each measurement: average over 3 runs\n\n";
    cout << "  Legend:\n";
    cout << "    S     = T(1 thread) / T(N threads)  -- actual speedup\n";
    cout << "    E     = S / N * 100%                -- parallel efficiency\n";
    cout << "    S_amd = theoretical limit (Amdahl)  -- upper bound\n\n";

    vector<BenchResult> all;

    for (int n : sizes) {
        cout << "+-- Matrix " << n << "x" << n
            << " ------------------------------------------------+\n";
        double t1 = bench(n, 1);
        cout << "|  T= 1  -> " << fixed << setprecision(2) << setw(10) << t1
            << " ms  (sequential baseline)\n";
        all.push_back({ n, 1, t1, 1.0, 100.0, 1.0 });

        for (int t : threads) {
            if (t == 1) continue;
            double tm = bench(n, t);
            double sp = t1 / tm;
            double eff = sp / t * 100.0;
            double am = 1.0 / ((1.0 - p) + p / (double)t);
            string comment;
            if (sp > am * 1.05)        comment = " << superlinear (cache effect!)";
            else if (sp >= am * 0.85)  comment = " << close to Amdahl theory";
            else if (sp < 1.0)         comment = " << overhead > work, too many threads";
            cout << "|  T=" << setw(2) << t << "  -> "
                << setw(10) << tm << " ms"
                << "  S=" << setprecision(3) << setw(5) << sp
                << "  E=" << setprecision(1) << setw(5) << eff << "%"
                << "  S_amd=" << setprecision(3) << setw(5) << am
                << "  " << speedup_bar(sp, (double)t)
                << comment << "\n";
            all.push_back({ n, t, tm, sp, eff, am });
        }
        cout << "+----------------------------------------------------------+\n\n";
    }

    // ── Summary ───────────────────────────────────────────────────────────────
    cout << "==============================================================\n";
    cout << "  SUMMARY: best thread count per matrix size\n";
    cout << "--------------------------------------------------------------\n";
    for (int n : sizes) {
        double best_sp = 0.0; int best_t = 1;
        for (auto& r : all)
            if (r.n == n && r.speedup > best_sp) { best_sp = r.speedup; best_t = r.threads; }
        cout << "  " << setw(6) << n << "x" << n
            << ":  best speedup = " << fixed << setprecision(2) << best_sp
            << "x  at T=" << best_t << "\n";
    }
    double s_max = 1.0 / (1.0 - p);
    cout << "==============================================================\n\n";
    cout << "  Amdahl Law: at p=0.82  S_max = " << fixed << setprecision(2) << s_max << "x\n";
    cout << "  (" << (1 - p) * 100 << "% of code is sequential => hard limit)\n\n";

    // ── Save CSV ──────────────────────────────────────────────────────────────
    {
        ofstream csv("benchmark_results.csv");
        csv << "matrix_size,threads,time_ms,speedup,efficiency_pct,amdahl_speedup\n";
        csv << fixed << setprecision(4);
        for (auto& r : all)
            csv << r.n << "," << r.threads << "," << r.time_ms << ","
            << r.speedup << "," << r.efficiency << "," << r.amdahl_speedup << "\n";
        cout << "  [OK] benchmark_results.csv saved\n";
    }

    // ── Write plot script ─────────────────────────────────────────────────────
    write_plot_script("benchmark_results.csv", "plot_results.py",
        sizes, threads, p, hw_threads);
    cout << "  [OK] plot_results.py written\n\n";

    // ── Auto-run Python ───────────────────────────────────────────────────────
    cout << "  Generating charts...\n";
    bool ok = run_python("plot_results.py");
    if (ok) {
        cout << "\n  Charts saved:\n";
        cout << "    chart_amdahl.png\n";
        cout << "    chart_speedup.png\n";
        cout << "    chart_efficiency.png\n";
        cout << "    chart_time.png\n";
    }
    else {
        cout << "\n  [!] Python not found in PATH.\n";
        cout << "      Install Python and run manually:\n";
        cout << "        pip install matplotlib pandas numpy\n";
        cout << "        python plot_results.py\n";
    }

    cout << "\n  Press Enter to exit...";
    cin.get();
    return 0;
}